language: node_js

node_js:
  - "lts/*"

if: tag is blank

cache:
  yarn: true
  directories:
    - node_module

script:
  - yarn type-check
  - yarn lint
  - yarn test:cov

after_success:
  - yarn coveralls

before_deploy:
  - yarn global add netlify-cli
  - yarn build:demo

deploy:
  provider: script
  script: netlify deploy --prod  --message "Deploy from Travis-CI" --site $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN --dir ./public
  skip_cleanup: true
  on:
    branch: master

notifications:
  email:
    on_failure: change
